# Autogenerated with SMOP 
from smop.core import *
# 

    
@function
def Read_Traj(dir=None,*args,**kwargs):
    varargin = Read_Traj.varargin
    nargin = Read_Traj.nargin

    #Read Trajectory from path
#In case the input is from raw input, feature selection might be required
#feature_selection need to be clear!!!!
# feature_selection = [1:19 ];
    data=csvread(dir)
# Read_Traj.m:6
    num_frame=size(data,1)
# Read_Traj.m:7
    t=arange(1,num_frame,1)
# Read_Traj.m:8
    data=matlabarray(cat(t.T,data))
# Read_Traj.m:9
    # traj = data(:,feature_selection);
    traj=copy(data)
# Read_Traj.m:11
    return traj
    
if __name__ == '__main__':
    pass
    